<?php
/**
 * BulkOrdersApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post International Shipping API - QA
 *
 * Welcome to the Deutsche Post International API! <br/><br/> This API provides an interface for our shipping and tracking services. It enables open integration channels for our customers and partners.
 *
 * The version of the OpenAPI document: 5.7.7
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\DHLParcel\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
#region SPY Code
use GuzzleHttp\Cookie\CookieJar;
#endregion
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Spy\DHLParcel\ApiException;
use Spy\DHLParcel\Configuration;
use Spy\DHLParcel\HeaderSelector;
use Spy\DHLParcel\ObjectSerializer;

/**
 * BulkOrdersApi Class Doc Comment
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BulkOrdersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

	#region SPY Code
	protected $bXDebugOnInstance	= false;
	protected $bXDebugOnNextRequest;

	/**
	 * @param bool $bXDebugOnInstance
	 * @return $this
	 */
	public function setXDebugOnInstance(bool $bXDebugOnInstance)
	{
		$this->bXDebugOnInstance	= $bXDebugOnInstance;

		return $this;
	}

	/**
	 * @return $this
	 */
	public function setXDebugOnNextRequest()
	{
		$this->bXDebugOnNextRequest	= true;

		return $this;
	}

	/**
	 * Gets the OpenAPI Spec Version
	 *
	 * @return string
	 */
	public static function getSpecVersion()
	{
		return '5.7.7';
	}
	#endregion

    /**
    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createBulkOrder' => [
            'application/json',
        ],
        'createMixedOrder' => [
            'application/json',
        ],
        'downloadBulkPaperwork' => [
            'application/json',
        ],
        'getBagTagLabel' => [
            'application/json',
        ],
        'getBulkOrder' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBulkOrder
     *
     * Create a Bulk Order
     *
     * @param  int $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\BagOrder $body The bag order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBulkOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\DHLParcel\Model\BagOrder|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO
     */
    public function createBulkOrder($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createBulkOrder'][0])
    {
        list($response) = $this->createBulkOrderWithHttpInfo($customer_ekp, $authorization, $body, $contentType);
        return $response;
    }

    /**
     * Operation createBulkOrderWithHttpInfo
     *
     * Create a Bulk Order
     *
     * @param  int $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\BagOrder $body The bag order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBulkOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\DHLParcel\Model\BagOrder|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBulkOrderWithHttpInfo($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createBulkOrder'][0])
    {
        $request = $this->createBulkOrderRequest($customer_ekp, $authorization, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\DHLParcel\Model\BagOrder' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\BagOrder' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\BagOrder', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\DHLParcel\Model\BagOrder';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\BagOrder',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createBulkOrderAsync
     *
     * Create a Bulk Order
     *
     * @param  int $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\BagOrder $body The bag order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBulkOrderAsync($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createBulkOrder'][0])
    {
        return $this->createBulkOrderAsyncWithHttpInfo($customer_ekp, $authorization, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBulkOrderAsyncWithHttpInfo
     *
     * Create a Bulk Order
     *
     * @param  int $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\BagOrder $body The bag order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBulkOrderAsyncWithHttpInfo($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createBulkOrder'][0])
    {
        $returnType = '\Spy\DHLParcel\Model\BagOrder';
        $request = $this->createBulkOrderRequest($customer_ekp, $authorization, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBulkOrder'
     *
     * @param  int $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\BagOrder $body The bag order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createBulkOrderRequest($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createBulkOrder'][0])
    {

        // verify the required parameter 'customer_ekp' is set
        if ($customer_ekp === null || (is_array($customer_ekp) && count($customer_ekp) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_ekp when calling createBulkOrder'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling createBulkOrder'
            );
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createBulkOrder'
            );
        }


        $resourcePath = '/dpi/shipping/v1/bulk/{customerEkp}/orders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($customer_ekp !== null) {
            $resourcePath = str_replace(
                '{' . 'customerEkp' . '}',
                ObjectSerializer::toPathValue($customer_ekp),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createMixedOrder
     *
     * Create a Mixed Order
     *
     * @param  string $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\MixedBagOrderDTO $body The mixed order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMixedOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\DHLParcel\Model\BulkOrderDto|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO
     */
    public function createMixedOrder($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createMixedOrder'][0])
    {
        list($response) = $this->createMixedOrderWithHttpInfo($customer_ekp, $authorization, $body, $contentType);
        return $response;
    }

    /**
     * Operation createMixedOrderWithHttpInfo
     *
     * Create a Mixed Order
     *
     * @param  string $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\MixedBagOrderDTO $body The mixed order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMixedOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\DHLParcel\Model\BulkOrderDto|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMixedOrderWithHttpInfo($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createMixedOrder'][0])
    {
        $request = $this->createMixedOrderRequest($customer_ekp, $authorization, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\DHLParcel\Model\BulkOrderDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\BulkOrderDto' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\BulkOrderDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\DHLParcel\Model\BulkOrderDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\BulkOrderDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMixedOrderAsync
     *
     * Create a Mixed Order
     *
     * @param  string $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\MixedBagOrderDTO $body The mixed order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMixedOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMixedOrderAsync($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createMixedOrder'][0])
    {
        return $this->createMixedOrderAsyncWithHttpInfo($customer_ekp, $authorization, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMixedOrderAsyncWithHttpInfo
     *
     * Create a Mixed Order
     *
     * @param  string $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\MixedBagOrderDTO $body The mixed order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMixedOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMixedOrderAsyncWithHttpInfo($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createMixedOrder'][0])
    {
        $returnType = '\Spy\DHLParcel\Model\BulkOrderDto';
        $request = $this->createMixedOrderRequest($customer_ekp, $authorization, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMixedOrder'
     *
     * @param  string $customer_ekp The customers ekp for whom the order shall be created. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  \Spy\DHLParcel\Model\MixedBagOrderDTO $body The mixed order that shall be created. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createMixedOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMixedOrderRequest($customer_ekp, $authorization, $body, string $contentType = self::contentTypes['createMixedOrder'][0])
    {

        // verify the required parameter 'customer_ekp' is set
        if ($customer_ekp === null || (is_array($customer_ekp) && count($customer_ekp) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_ekp when calling createMixedOrder'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling createMixedOrder'
            );
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createMixedOrder'
            );
        }


        $resourcePath = '/dpi/shipping/v1/bulk/{customerEkp}/mixedorders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($customer_ekp !== null) {
            $resourcePath = str_replace(
                '{' . 'customerEkp' . '}',
                ObjectSerializer::toPathValue($customer_ekp),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation downloadBulkPaperwork
     *
     * Get Bulk Paperwork
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order from paperwork that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadBulkPaperwork'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\DHLParcel\Model\Order|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO
     */
    public function downloadBulkPaperwork($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['downloadBulkPaperwork'][0])
    {
        list($response) = $this->downloadBulkPaperworkWithHttpInfo($customer_ekp, $order_id, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation downloadBulkPaperworkWithHttpInfo
     *
     * Get Bulk Paperwork
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order from paperwork that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadBulkPaperwork'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\DHLParcel\Model\Order|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function downloadBulkPaperworkWithHttpInfo($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['downloadBulkPaperwork'][0])
    {
        $request = $this->downloadBulkPaperworkRequest($customer_ekp, $order_id, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\DHLParcel\Model\Order' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\Order' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\Order', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\DHLParcel\Model\Order';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\Order',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation downloadBulkPaperworkAsync
     *
     * Get Bulk Paperwork
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order from paperwork that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadBulkPaperwork'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadBulkPaperworkAsync($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['downloadBulkPaperwork'][0])
    {
        return $this->downloadBulkPaperworkAsyncWithHttpInfo($customer_ekp, $order_id, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation downloadBulkPaperworkAsyncWithHttpInfo
     *
     * Get Bulk Paperwork
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order from paperwork that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadBulkPaperwork'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadBulkPaperworkAsyncWithHttpInfo($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['downloadBulkPaperwork'][0])
    {
        $returnType = '\Spy\DHLParcel\Model\Order';
        $request = $this->downloadBulkPaperworkRequest($customer_ekp, $order_id, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'downloadBulkPaperwork'
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order from paperwork that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadBulkPaperwork'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function downloadBulkPaperworkRequest($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['downloadBulkPaperwork'][0])
    {

        // verify the required parameter 'customer_ekp' is set
        if ($customer_ekp === null || (is_array($customer_ekp) && count($customer_ekp) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_ekp when calling downloadBulkPaperwork'
            );
        }

        // verify the required parameter 'order_id' is set
        if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling downloadBulkPaperwork'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling downloadBulkPaperwork'
            );
        }


        $resourcePath = '/dpi/shipping/v1/bulk/{customerEkp}/orders/{orderId}/paperwork';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($customer_ekp !== null) {
            $resourcePath = str_replace(
                '{' . 'customerEkp' . '}',
                ObjectSerializer::toPathValue($customer_ekp),
                $resourcePath
            );
        }
        // path params
        if ($order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($order_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/octet-stream', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBagTagLabel
     *
     * Get Bag Tag Label
     *
     * @param  string[] $bag_ids The ids of the bag seperated by commas e.g. bagIds&#x3D;GM40040404040410000000000035,GM40040404040410000000000036 (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $accept Bytestream containing the media type of the generated label. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBagTagLabel'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getBagTagLabel($bag_ids, $authorization, $accept, string $contentType = self::contentTypes['getBagTagLabel'][0])
    {
        $this->getBagTagLabelWithHttpInfo($bag_ids, $authorization, $accept, $contentType);
    }

    /**
     * Operation getBagTagLabelWithHttpInfo
     *
     * Get Bag Tag Label
     *
     * @param  string[] $bag_ids The ids of the bag seperated by commas e.g. bagIds&#x3D;GM40040404040410000000000035,GM40040404040410000000000036 (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $accept Bytestream containing the media type of the generated label. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBagTagLabel'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBagTagLabelWithHttpInfo($bag_ids, $authorization, $accept, string $contentType = self::contentTypes['getBagTagLabel'][0])
    {
        $request = $this->getBagTagLabelRequest($bag_ids, $authorization, $accept, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBagTagLabelAsync
     *
     * Get Bag Tag Label
     *
     * @param  string[] $bag_ids The ids of the bag seperated by commas e.g. bagIds&#x3D;GM40040404040410000000000035,GM40040404040410000000000036 (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $accept Bytestream containing the media type of the generated label. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBagTagLabel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBagTagLabelAsync($bag_ids, $authorization, $accept, string $contentType = self::contentTypes['getBagTagLabel'][0])
    {
        return $this->getBagTagLabelAsyncWithHttpInfo($bag_ids, $authorization, $accept, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBagTagLabelAsyncWithHttpInfo
     *
     * Get Bag Tag Label
     *
     * @param  string[] $bag_ids The ids of the bag seperated by commas e.g. bagIds&#x3D;GM40040404040410000000000035,GM40040404040410000000000036 (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $accept Bytestream containing the media type of the generated label. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBagTagLabel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBagTagLabelAsyncWithHttpInfo($bag_ids, $authorization, $accept, string $contentType = self::contentTypes['getBagTagLabel'][0])
    {
        $returnType = '';
        $request = $this->getBagTagLabelRequest($bag_ids, $authorization, $accept, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBagTagLabel'
     *
     * @param  string[] $bag_ids The ids of the bag seperated by commas e.g. bagIds&#x3D;GM40040404040410000000000035,GM40040404040410000000000036 (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $accept Bytestream containing the media type of the generated label. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBagTagLabel'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBagTagLabelRequest($bag_ids, $authorization, $accept, string $contentType = self::contentTypes['getBagTagLabel'][0])
    {

        // verify the required parameter 'bag_ids' is set
        if ($bag_ids === null || (is_array($bag_ids) && count($bag_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bag_ids when calling getBagTagLabel'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling getBagTagLabel'
            );
        }

        // verify the required parameter 'accept' is set
        if ($accept === null || (is_array($accept) && count($accept) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accept when calling getBagTagLabel'
            );
        }


        $resourcePath = '/dpi/shipping/v1/bulk/label';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bag_ids,
            'bagIds', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            true // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }
        // header params
        if ($accept !== null) {
            $headerParams['accept'] = ObjectSerializer::toHeaderValue($accept);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/pdf', 'application/pdf+singlepage', 'application/zpl', 'application/zpl+rotated', 'image/png', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBulkOrder
     *
     * Get a Bulk Order
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBulkOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Spy\DHLParcel\Model\Order|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO
     */
    public function getBulkOrder($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['getBulkOrder'][0])
    {
        list($response) = $this->getBulkOrderWithHttpInfo($customer_ekp, $order_id, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getBulkOrderWithHttpInfo
     *
     * Get a Bulk Order
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBulkOrder'] to see the possible values for this operation
     *
     * @throws \Spy\DHLParcel\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Spy\DHLParcel\Model\Order|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO|\Spy\DHLParcel\Model\CwsErrorDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBulkOrderWithHttpInfo($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['getBulkOrder'][0])
    {
        $request = $this->getBulkOrderRequest($customer_ekp, $order_id, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Spy\DHLParcel\Model\Order' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\Order' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\Order', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Spy\DHLParcel\Model\CwsErrorDTO' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Spy\DHLParcel\Model\CwsErrorDTO' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Spy\DHLParcel\Model\CwsErrorDTO', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Spy\DHLParcel\Model\Order';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\Order',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Spy\DHLParcel\Model\CwsErrorDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBulkOrderAsync
     *
     * Get a Bulk Order
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBulkOrderAsync($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['getBulkOrder'][0])
    {
        return $this->getBulkOrderAsyncWithHttpInfo($customer_ekp, $order_id, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBulkOrderAsyncWithHttpInfo
     *
     * Get a Bulk Order
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBulkOrderAsyncWithHttpInfo($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['getBulkOrder'][0])
    {
        $returnType = '\Spy\DHLParcel\Model\Order';
        $request = $this->getBulkOrderRequest($customer_ekp, $order_id, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBulkOrder'
     *
     * @param  string $customer_ekp The customers ekp for who retrieves the order. (required)
     * @param  string $order_id The id of the order that the user wants to retrieve. (required)
     * @param  string $authorization Bearer Auth access_token together with the \&quot;Bearer\&quot; prefix is required. **Example** of the header value:\&quot;*Bearer 0UuA.....*\&quot; (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBulkOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBulkOrderRequest($customer_ekp, $order_id, $authorization, string $contentType = self::contentTypes['getBulkOrder'][0])
    {

        // verify the required parameter 'customer_ekp' is set
        if ($customer_ekp === null || (is_array($customer_ekp) && count($customer_ekp) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_ekp when calling getBulkOrder'
            );
        }

        // verify the required parameter 'order_id' is set
        if ($order_id === null || (is_array($order_id) && count($order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling getBulkOrder'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling getBulkOrder'
            );
        }


        $resourcePath = '/dpi/shipping/v1/bulk/{customerEkp}/orders/{orderId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($customer_ekp !== null) {
            $resourcePath = str_replace(
                '{' . 'customerEkp' . '}',
                ObjectSerializer::toPathValue($customer_ekp),
                $resourcePath
            );
        }
        // path params
        if ($order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orderId' . '}',
                ObjectSerializer::toPathValue($order_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

		#region SPY Code
		$options[RequestOptions::HEADERS]	= [
			'X-OpenAPISpecVersion'	=> '5.7.7',
		];
		$bEnableXDebug	= $this->bXDebugOnNextRequest;

		if($bEnableXDebug === null)
		{
			$bEnableXDebug	= $this->bXDebugOnInstance;
		}

		$this->bXDebugOnNextRequest	= null;

		if($bEnableXDebug)
		{
			if(preg_match('/^(?:https?:\/\/)?([^\/:]+\.[^\/:]+)/i', $this->getConfig()->getHost(), $arrMatches) === 1)
			{
				$options['cookies'] = CookieJar::fromArray(
					[
						'XDEBUG_SESSION'	=> 'PHPSTORM',
					],
					$arrMatches[1]
				);
			}
		}
		#endregion

        return $options;
    }
}
