<?php
/**
 * ItemModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post International Shipping API - QA
 *
 * Welcome to the Deutsche Post International API! <br/><br/> This API provides an interface for our shipping and tracking services. It enables open integration channels for our customers and partners.
 *
 * The version of the OpenAPI document: 5.7.7
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\DHLParcel\Model;

/**
 * ItemModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemModelFields
{
    public string $strAddressLine1 = 'addressLine1';
    public string $strAddressLine2 = 'addressLine2';
    public string $strAddressLine3 = 'addressLine3';
    public string $strBarcode = 'barcode';
    public string $strCity = 'city';
    public string $strContents = 'contents';
    public string $strCustRef = 'custRef';
    public string $strCustRef2 = 'custRef2';
    public string $strCustRef3 = 'custRef3';
    public string $strDestinationCountry = 'destinationCountry';
    public string $strId = 'id';
    public string $strPostalCode = 'postalCode';
    public string $strProduct = 'product';
    public string $strImporterTaxId = 'importerTaxId';
    public string $strRecipient = 'recipient';
    public string $strRecipientEmail = 'recipientEmail';
    public string $strRecipientFax = 'recipientFax';
    public string $strRecipientPhone = 'recipientPhone';
    public string $strReturnItemWanted = 'returnItemWanted';
    public string $strPDdp = 'pDDP';
    public string $strSenderAddressLine1 = 'senderAddressLine1';
    public string $strSenderAddressLine2 = 'senderAddressLine2';
    public string $strSenderCity = 'senderCity';
    public string $strSenderCountry = 'senderCountry';
    public string $strSenderEmail = 'senderEmail';
    public string $strSenderName = 'senderName';
    public string $strSenderPhone = 'senderPhone';
    public string $strSenderPostalCode = 'senderPostalCode';
    public string $strSenderTaxId = 'senderTaxId';
    public string $strServiceLevel = 'serviceLevel';
    public string $strShipmentAmount = 'shipmentAmount';
    public string $strShipmentCurrency = 'shipmentCurrency';
    public string $strShipmentGrossWeight = 'shipmentGrossWeight';
    public string $strShipmentNaturetype = 'shipmentNaturetype';
    public string $strState = 'state';
    public string $strThirdPartyVendorId = 'thirdPartyVendorId';
    public string $strFormat = 'format';
}

