<?php
/**
 * ResponseItemModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.9
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\DHLParcel\Model;

/**
 * ResponseItemModelFields Class Doc Comment
 *
 * @category Class
 * @description Response for a single shipment containing status, numbers and labels
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResponseItemModelFields
{
    public string $strShipmentNo = 'shipmentNo';
    public string $strRoutingCode = 'routingCode';
    public string $strReturnShipmentNo = 'returnShipmentNo';
    public string $strSstatus = 'sstatus';
    public string $strShipmentRefNo = 'shipmentRefNo';
    public string $strLabel = 'label';
    public string $strReturnLabel = 'returnLabel';
    public string $strCustomsDoc = 'customsDoc';
    public string $strCodLabel = 'codLabel';
    public string $strValidationMessages = 'validationMessages';
}

