<?php
/**
 * ShipmentModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.9
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\DHLParcel\Model;

/**
 * ShipmentModelFields Class Doc Comment
 *
 * @category Class
 * @description Container for all shipments. Mixed shipment products per request are supported. Each shipment has a dedicated shipper address (or shipper reference, or both).
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentModelFields
{
    public string $strProduct = 'product';
    public string $strBillingNumber = 'billingNumber';
    public string $strRefNo = 'refNo';
    public string $strCostCenter = 'costCenter';
    public string $strCreationSoftware = 'creationSoftware';
    public string $strShipDate = 'shipDate';
    public string $strShipper = 'shipper';
    public string $strConsignee = 'consignee';
    public string $strDetails = 'details';
    public string $strServices = 'services';
    public string $strCustoms = 'customs';
}

