<?php
/**
 * TrackingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post International Shipping API - QA
 *
 * Welcome to the Deutsche Post International API! <br/><br/> This API provides an interface for our shipping and tracking services. It enables open integration channels for our customers and partners.
 *
 * The version of the OpenAPI document: 5.7.7
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Spy\DHLParcel\Test\Api;

use \Spy\DHLParcel\Configuration;
use \Spy\DHLParcel\ApiException;
use \Spy\DHLParcel\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TrackingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spy\DHLParcel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrackingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBagAndEvents
     *
     * Get Trackings of bags V3.
     *
     */
    public function testGetBagAndEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingForAirwayBill
     *
     * Get Tracking - Shipment V3.
     *
     */
    public function testGetTrackingForAirwayBill()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingForAwb
     *
     * Get Tracking - Shipment V1.
     *
     */
    public function testGetTrackingForAwb()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingsBasic
     *
     * Get Trackings V1.
     *
     */
    public function testGetTrackingsBasic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingsExtended
     *
     * Get Trackings V3.
     *
     */
    public function testGetTrackingsExtended()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
